@startuml
!define BGCOLOR white
skinparam backgroundColor BGCOLOR
skinparam sequenceMessageAlign center

actor User
participant "<u>:SpendTrack</u>" as ST
participant "<<class>>\nParser" as P
participant "<u>:Command</u>" as CMD
participant "<u>:ExpenseList</u>" as EL
participant "<u>:Storage</u>" as S
participant "<u>:Ui</u>" as UI

User -> ST : launch app
activate ST

ST -> S : load(expenseList)
activate S
S --> ST
deactivate S

ST -> UI : showWelcome()
activate UI
UI --> User : welcome message
deactivate UI

loop until isExit
    UI --> User : "> " prompt
    User -> ST : input string
    ST -> P : parse(input)
    activate P
    P --> ST : :Command
    deactivate P

    ST -> CMD : execute(expenseList, ui)
    activate CMD
    CMD -> EL : read / mutate
    activate EL
    EL --> CMD
    deactivate EL
    CMD -> UI : show result
    activate UI
    UI --> User : output
    deactivate UI
    CMD --> ST
    deactivate CMD

    opt command.mutatesData()
        ST -> S : save(expenseList)
        activate S
        S --> ST
        deactivate S
    end

    opt command.isExit()
        ST -> ST : isRunning = false
    end
end

deactivate ST
@enduml
