@startuml
!define BGCOLOR white
skinparam backgroundColor BGCOLOR
skinparam sequenceMessageAlign center

actor User
participant "<u>:SpendTrack</u>" as ST
participant "<<class>>\nParser" as P
participant "<u>:ClearCommand</u>" as CC
participant "<u>:ExpenseList</u>" as EL
participant "<u>:Ui</u>" as UI

User -> ST : "clear"
activate ST

ST -> P : parse("clear")
activate P
P --> ST : :ClearCommand
deactivate P

ST -> CC : execute(expenses, ui)
activate CC

CC -> EL : size()
activate EL
EL --> CC : size
deactivate EL

alt size == 0
    CC -> UI : showMessage("No expenses to clear.")
    activate UI
    UI --> CC
    deactivate UI
else size > 0
    CC -> UI : showMessage("Are you sure...? (yes/no):")
    activate UI
    UI --> CC
    deactivate UI
    CC -> UI : readCommand()
    activate UI
    User -> UI : userInput
    UI --> CC : userInput
    deactivate UI
    alt userInput == "yes"
        CC -> EL : clearAll()
        activate EL
        EL --> CC
        deactivate EL
        CC -> UI : showMessage("All expenses cleared.")
        activate UI
        UI --> CC
        deactivate UI
    else any other input
        CC -> UI : showMessage("Clear cancelled.")
        activate UI
        UI --> CC
        deactivate UI
    end
end

CC --> ST
deactivate CC

ST --> User : output
ST -> ST : storage.save(expenses)

deactivate ST
@enduml
