@startuml
!define BGCOLOR white
skinparam backgroundColor BGCOLOR
skinparam sequenceMessageAlign center

actor User
participant "<u>:SpendTrack</u>" as ST
participant "<<class>>\nParser" as P
participant "<u>:ExpenseList</u>" as EL
participant "<u>:Ui</u>" as UI

note over ST, UI : Add recurring expense

User -> ST : "add d/Netflix a/18.00 c/Entertainment recurring/true"
activate ST
ST -> P : parse(input)
activate P
P -> P : parseAddCommand(args)
note right of P
    Extracts recurring/true token
    validates value is true or false
end note

create participant "<u>:AddCommand</u>" as AC
P -> AC : new AddCommand(..., isRecurring=true)
activate AC
AC --> P
deactivate AC

P --> ST : :AddCommand
deactivate P

ST -> AC : execute(expenseList, ui)
activate AC
AC -> "<u>:Expense</u>" as E ** : new Expense(..., isRecurring=true)
AC -> EL : addExpense(expense)
activate EL
EL --> AC
deactivate EL
AC -> UI : showAddSuccess(expense)
activate UI
UI --> AC
deactivate UI
AC --> ST : "New expense added: ... [R]"
deactivate AC
ST --> User : "New expense added: ... [R]"
deactivate ST

note over ST, UI : List recurring expenses

User -> ST : "list recurring"
activate ST
ST -> P : parse("list recurring")
activate P

create participant "<u>:ListCommand</u>" as LC
P -> LC : new ListCommand(recurringOnly=true)
activate LC
LC --> P
deactivate LC

P --> ST : :ListCommand
deactivate P

ST -> LC : execute(expenseList, ui)
activate LC
LC -> UI : showRecurringList(expenses)
activate UI
UI -> EL : getExpense(i) for each i
activate EL
EL --> UI : expense
deactivate EL
note right of UI
    Filters expenses where
    isRecurring == true
end note
UI --> LC : recurring expense table
deactivate UI
LC --> ST
deactivate LC
ST --> User : recurring expense table
deactivate ST
@enduml