@startuml
!define BGCOLOR white
skinparam backgroundColor BGCOLOR
skinparam sequenceMessageAlign center

actor User
participant "<u>:SpendTrack</u>" as ST
participant "<<class>>\nParser" as P
participant "<u>:RemainingCommand</u>" as RC
participant "<u>:ExpenseList</u>" as EL
participant "<u>:Ui</u>" as UI

User -> ST : "remaining"
activate ST

ST -> P : parse(input)
activate P
create "<u>:RemainingCommand</u>" as RC
P -> RC : new RemainingCommand()
activate RC
RC --> P
deactivate RC
P --> ST : :RemainingCommand
deactivate P

ST -> RC : execute(expenses, ui)
activate RC

RC -> EL : hasBudget()
activate EL

alt no budget set
    EL --> RC : false
    deactivate EL
    RC --> ST : throw SpendTrackException
    ST -> UI : showError("No budget set...")
    activate UI
    UI --> ST
    deactivate UI
    ST --> User : "No budget set..."
else budget set
    EL --> RC : true
    deactivate EL
    RC -> EL : getBudget()
    activate EL
    EL --> RC : 500.0
    deactivate EL
    RC -> EL : getTotal()
    activate EL
    EL --> RC : 87.30
    deactivate EL
    RC -> UI : showRemaining(500.0, 87.30, 412.70)
    activate UI
    UI --> RC
    deactivate UI
    RC --> ST
    ST --> User : "Remaining: $412.70"
end

deactivate RC
deactivate ST
@enduml